### ISSUE TITLE
Rich Text component enhancements

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/bbui#151]
The Rich Text component needs a couple of features to be feature complete:
- Custom theme that works well with Budibase
- Pasting MD/HTML should convert nicely
- Custom theme that works well with Budibase (and an upcoming Dark Theme? 🤫)
- Custom functionality to insert mustache bindings
- ???

Some inspiration: https://github.com/quilljs/awesome-quill

**Comment by aptkingston** [comment]
In order to use it in automation settings for things like email body, we'd need some sort of custom plugin to insert mustache bindings. That sounds kinda complicated though so might be outside the scope of this! Maybe it's possible to do insert text programatically via it's API though which would simplify things.

**Comment by kevmodrome** [comment]
Quill has a nice Clipboard module that handles copy, cut and paste to and from external apps that we can probably extend with any functionality we need: https://quilljs.com/docs/modules/clipboard/
